# Generated by Django 3.1.4 on 2020-12-06 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('is_mvp', models.BooleanField(default=0)),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d/')),
            ],
        ),
    ]
